appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: s17qMFyY7KabIyj8YWLbE0Tg4UNDshy8zf+OZhgfnXebSpqthzCJbOYqNAxjchzccL0fa+c2Zi47p/CPtVn3ol9d+vGWC872lgxVhLEEtofx2hJcnaX+DmHkdNWdkZER/JMOqOlwfoASBpwi85YLAuD+DfpRHSddpmvcvjIKQIYBaga6Pg99ZQWmcIDKW2gSxbQfBuyPXLrnJ8v9LewolfelN8hCjOuCB5XpR9+Ks+FjrDmVLbzREJSjRjlMn58zTcabyEjtwcanJ8Sq50Zj0yR0poAr5vStDfYFFnjhWi2jFY5GRReGyTiSVRuQxvg2GXpEJKFseXr04DWQS/yooWhKHrHia6Xx76QSYkotBduvGKqhSBneZrwNfPkA72BNVOpEz9wZmxj5xaJOtk2pG8Msxksq4vXP4Yd33wOMMSBrxLwqtlRJNrLlOHDIqY2c8Paxv0LA6Y0kHUcSbV+AxZJWvlD63TXpml3BFqZGQ0fMBQqiSOn/OQ5YsQg3MMYFKcaMc9gjh8gwWqodGre8lfJXbqdo8IN/TvETLc3Ey6FTy3N+xqOuzG1Yg8p62wMhJdsu4TspSowwbno5FXIhpzjdI6SktVR1juI34Jm3WitwhUNzOlG+th7ZJk0Ov3HeIH3t66yrtkdg3HKDrHcIihFztum4kI9bkHlsKf4e68w=}
provider:
  osx: circle
  linux: circle
  

